#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# MagicTouch
#
# Copyright (C) 2011
#    Benedikt Seidl, <Benedikt.Seidl at gmx dot de>
#
# This file is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

import sys

try:
    import magictouch
except ImportError:
    sys.path = ['..', '/usr/share/games'] + sys.path

    try:
        import magictouch
    except ImportError:
        sys.stderr.write('ERROR: Cannot find magictouch package: reinstall the game.\n')
        sys.exit(1)

if __name__ == '__main__':
    magictouch.MagicTouch.start()

